<a href="https://colab.research.google.com/github/robertosgpontes/tec_prog_1/blob/main/ExerciciosNumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

## Questão 1

Crie um array 100 com valores aleatórios e ache os valores máximo e mínimo

In [7]:
arr = np.random.rand(100)
# arr = np.random.randint(0, 100, 100)
print(f'array: {arr}')
arr_max, arr_min = max(arr), min(arr)
print(f'valor max: {arr_max}, valor min: {arr_min}')

array: [0.20702892 0.47264068 0.14546102 0.61713166 0.13251071 0.20367119
 0.11333402 0.36056732 0.88632409 0.36272178 0.94158977 0.82211108
 0.44532553 0.28158824 0.39441032 0.5639596  0.67191585 0.48175991
 0.94586011 0.47974291 0.95943941 0.54834578 0.76570692 0.70309232
 0.65864489 0.56622801 0.2966015  0.64762667 0.74849013 0.02218229
 0.25854054 0.86741892 0.20539187 0.20760543 0.2441577  0.24806877
 0.88692161 0.26447038 0.27662834 0.5534996  0.87104428 0.35392001
 0.91121722 0.06645343 0.01246683 0.93017041 0.98393904 0.87342325
 0.71812717 0.67279501 0.44182378 0.51427015 0.23554956 0.75222352
 0.6984564  0.97858633 0.24796572 0.62610283 0.08795707 0.56838365
 0.00629447 0.51335284 0.59924716 0.70989833 0.04195423 0.41900894
 0.82526156 0.63685101 0.73940578 0.71634822 0.47715885 0.02621765
 0.50281769 0.21458939 0.6104322  0.77973384 0.7451347  0.39219217
 0.1192852  0.0216323  0.18288186 0.92797395 0.71649834 0.25032051
 0.95665681 0.49369348 0.12135887 0.83844329 0.21736474

## Questão 2
Em Geometria Analítica, um **vetor** é uma quantidade que pode ser definida por um énuplo (uma sequência ordenada de *n* elementos) em que cada elemento representa a intensidade do vetor na direção especificada pela i-ésima componente desta sequência. 

Quando pensamos em duas dimensões, por exemplo, o vetor $R = (b,a)$ define, geometricamente, a entidade representada na figura abaixo, com componentes nos eixos x e y usuais.

<img src = "https://static.todamateria.com.br/upload/im/ag/image-721.jpg?auto_optimize=low" />

O **módulo** deste vetor, também chamado de intensidade, está geometricamente relacionado ao seu comprimento, e pode ser calculado diretamente pelas suas componentes, por meio de uma operação conhecida como **produto escalar** do vetor com ele mesmo. O módulo quadrático é expresso, desta forma, por:

$|A|^2 = \vec{A} \cdot \vec{A}$

Por outro lado, o produto escalar entre dois vetores $A = (a_{x}, a_{y})$ e $B = (b_{x}, b_{y})$ é dado por:

$\vec{A} \cdot \vec{B} = a_{x} \times b_{x} + a_{y} \times b_{y}$ (e esta definição vale para qualquer que seja a dimensão do vetor).

O módulo quadrático de um vetor é, portanto:

$|A|² = a_{x}^2 + b_{x}^2$.

Dado o exposto acima, escreva uma função que retorne o módulo de um vetor n-dimensional qualquer.

In [12]:
arr = np.sort(np.random.randint(0, 10, 10))
print(f'vetor: {arr}')
modulo = np.linalg.norm(arr)
modulo_quad = np.dot(arr, arr)
print(f'modulo: {modulo}, modulo quadrático: {modulo_quad}, ')


vetor: [0 1 2 2 3 4 5 7 8 9]
modulo: 15.905973720586866, modulo quadrático: 253, 


## Questão 3

Em uma **análise de regressão**, usualmente estamos interessados em descrever relações entre variáveis de um dado conjunto de dados por meio de uma **função** que descreva, o tanto quanto possível, estas relações.

Por exemplo, no gráfico abaixo, os pontos vermelhos relacionam as medidas das duas variáveis sendo avaliadas (nos eixos x e y); e a linha azul aproxima a relação entre elas por uma função linear.

![Normdist_regression.png](https://miro.medium.com/v2/resize:fit:786/format:webp/1*LEmBCYAttxS6uI6rEyPLMQ.png)

É possível ver que nem todos os pontos obedecem exatamente à relação ditada pela reta (isto é, há pontos que não estão exatamente "sobre a reta"; mas, sim, ligeraimente acima, ou abaixo, dela). Isto, contudo, é esperado em um modelo de regressão, por inúmeras fontes de incerteza associadas às medições.

Uma das métricas que utilizamos para avaliar a qualidade de uma regressão é o **erro quadrático médio (EQM)**, que mensura a diferença total entre cada predição da regressão ($y_{prediction}$; que no nosso caso seriam os valores de y para a reta azul) com o valor real de cada i-ésima medida ($y_{i}$; que no nosso caso seriam as coordenadas y para cada ponto vermelho do gráfico). O EQM pode ser definido como:

$EQM = \frac{1}{n}\sum_{i=1}^{n}(y_{prediction} - y_{i})^2$.

Isto posto, escreva uma função que calcule o EQM recebendo, como entrada, os vetores $y_{prediction}$ e $y_{i}$. Por exemplo, digamos que sua função se chame *calculate_eqm*, ela deve operar da seguinte forma:

```python

# dados dois arrays quaisquer de mesmo tamanho, a função deve retornar o EQM
y_prediction = np.array([1,2,3])
y_i = np.array([0,0,3])
calculate_eqm(y_prediction,y_i)

>>> 1.6666666666666665

```

In [18]:
# Solução
def calculate_eqm(y_prediction, y_i):
    return np.mean((y_prediction - y_i)**2)

y_prediction = np.array([1,2,3])
y_i = np.array([0,0,3])
print(calculate_eqm(y_prediction,y_i))

1.6666666666666667


## Questão 4

Crie um array 2D (bidimensional) com 1 na borda e 0 dentro

In [37]:
def arr_2d_bordas(arr_2d, char):
    linhas, colunas = arr_2d.shape
    for i in range(linhas): # itera sobre linhas
        for j in range(colunas): # itera sobre colunas
            if i == 0 or i == (linhas-1): # checa se é a primeira ou a ultima linha
                arr_2d[i, j] = char
            if j == 0 or j == (colunas-1): # checa se é a primeira ou a ultima coluna
                arr_2d[i, j] = char
    return arr_2d

arr_2d = np.zeros((4,4), dtype=int)
print(f'{arr_2d} \n\n {arr_2d_bordas(arr_2d, 1)}')


[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]] 

 [[1 1 1 1]
 [1 0 0 1]
 [1 0 0 1]
 [1 1 1 1]]


## Questão 5

Como adicionar uma borda de 0's ao redor de um array 2D (bidimensional) existente

In [40]:
arr_2d = np.ones((4,4), dtype=int)
print(arr_2d)

borda_arr = np.pad(arr_2d, pad_width=1, mode='constant', constant_values=0)
print(borda_arr)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[0 0 0 0 0 0]
 [0 1 1 1 1 0]
 [0 1 1 1 1 0]
 [0 1 1 1 1 0]
 [0 1 1 1 1 0]
 [0 0 0 0 0 0]]


## Questão 6

 A eletroencefalografia (EEG) é uma técnica que mensura potenciais elétricos cerebrais em diversas regiões do escalpo do paciente. Suponha que você recebeu um conjunto de dados na forma de uma matriz de 64 x 512 elementos, em que cada linha contém o sinal gravado em um dos **eletrodos** espalhados pelo escalpo em um exame de EEG, e cada coluna contém um valor de potencial elétrico, em microvolts. 

Como o sinal de EEG é muito suscetível a ruídos externos (interferências na qualidade do sinal), uma operação comum para atenuar a interferência no sinal consiste em tirar a média do potencial elétrico de todos os eletrodos, e subtrair este valor de cada um deles. Isto atenua fontes de ruído ao sinal comuns a todos os eletrodos. Em termos matemáticos, o sinal processado por esta operação, $X_{e,i}$ para cada eletrodo (e) e amostra (i), é dado por:

$X_{e,i} = \hat{X_{e,i}} - \frac{1}{N}\sum_{e=1}^{N}\hat{X_{e,i}}$,

em que $\hat{X_{e,i}}$ representa o sinal original (ou seja, é a matriz de entrada de 64 x 512 elementos), e $N$ indica o total de eletrodos.

Com o exposto acima, escreva uma função que retorne uma matriz com os sinais de EEG processados conforme a operação mencionada. Sua função deve operar conforme o exemplo abaixo.

```python

# vamos supor uma matriz de entrada gerada por dados aleatórios
X = np.random.randn(64,512)
X.shape # apenas para verificar as dimensões
>>> (64, 512)

# a função deve executar a operação equacionada anteriormente, retornando uma nova matriz
X_processado = process_EEG_signal(X)
X_processado.shape
>>> (64, 512)

# Somando as diferenças entre cada elemento das duas matrizes, apenas para ilustrar que elas não são iguais
(X_processado - X).sum()
>>> -53.08727366483029

# Visualizando as matrizes, para verificar uma vez mais que, de fato, os elementos são diferentes
X
>>> array([[ 0.29305925,  0.89663038, -0.61032202, ..., -0.88086364,
        -0.8818789 ,  0.51260497],
       [-0.01274415,  1.05439522,  0.47958092, ..., -2.15387924,
         0.70721168,  0.97029889],
       [ 1.09478371, -0.16120847,  1.58400361, ...,  0.20981813,
         2.17373837,  0.94032162],
       ...,
       [-0.45294842, -2.28939505,  1.10111998, ...,  1.63581703,
        -0.39394924, -1.13400723],
       [-0.22669886,  0.25413429, -1.17870637, ..., -0.09509442,
         0.90733806,  0.37999411],
       [ 0.15476933, -0.03654717, -1.09982762, ...,  0.67600047,
        -0.84533328, -0.56433144]])

# Matriz após o processamento descrito no enunciado
X_processado

>>> array([[ 0.36713022,  0.85772513, -0.54902169, ..., -0.85626087,
        -0.97611435,  0.51718998],
       [ 0.06132682,  1.01548997,  0.54088126, ..., -2.12927647,
         0.61297623,  0.97488389],
       [ 1.16885469, -0.20011372,  1.64530394, ...,  0.23442091,
         2.07950292,  0.94490663],
       ...,
       [-0.37887744, -2.3283003 ,  1.16242031, ...,  1.6604198 ,
        -0.4881847 , -1.12942223],
       [-0.15262788,  0.21522904, -1.11740604, ..., -0.07049164,
         0.81310261,  0.38457911],
       [ 0.22884031, -0.07545242, -1.03852729, ...,  0.70060324,
        -0.93956874, -0.55974643]])

```

In [59]:
# Solução

def process_ECG_matrix(ecg_matrix):
    process_matrix = ecg_matrix.copy()
    media = np.mean(ecg_matrix)
    # linhas, colunas = ecg_matrix.shape
    # for i in range(linhas):
    #     for j in range(colunas):
    #         process_matrix[i, j] = ecg_matrix[i, j] - media
    #         #print(f'pos{i, j}: {ecg_matrix[i, j]} - {media} = {process_matrix[i, j]}')
    process_matrix -= media
    return process_matrix

ecg_matrix = np.random.rand(64, 512)

process_matrix = process_ECG_matrix(ecg_matrix)

print(f'sinal puro: {ecg_matrix[:, :]} \n\n media: {np.mean(ecg_matrix)} \n\n sinal processado: {process_matrix[:, :]}')


sinal puro: [[0.74712726 0.65880918 0.6435218  ... 0.93175201 0.74575392 0.92690853]
 [0.91464754 0.34581609 0.1393361  ... 0.19049155 0.44933249 0.64080655]
 [0.02133573 0.77083124 0.70631068 ... 0.50898892 0.38150556 0.86215251]
 ...
 [0.25789308 0.17207089 0.1789946  ... 0.79310196 0.23556521 0.01141173]
 [0.05856417 0.99529194 0.75650627 ... 0.81214395 0.88411558 0.19395718]
 [0.4858172  0.83795158 0.38291561 ... 0.2766867  0.46980018 0.96902933]] 

 media: 0.5002881726879276 

 sinal processado: [[ 0.24683908  0.15852101  0.14323363 ...  0.43146384  0.24546575
   0.42662036]
 [ 0.41435937 -0.15447208 -0.36095207 ... -0.30979662 -0.05095568
   0.14051838]
 [-0.47895244  0.27054307  0.20602251 ...  0.00870075 -0.11878261
   0.36186433]
 ...
 [-0.24239509 -0.32821728 -0.32129357 ...  0.29281379 -0.26472296
  -0.48887644]
 [-0.441724    0.49500377  0.25621809 ...  0.31185578  0.38382741
  -0.30633099]
 [-0.01447098  0.33766341 -0.11737257 ... -0.22360147 -0.030488
   0.46874115]]


## Questão 7

Em estatística, um **outlier** é um valor que destoa consideravelmente da distribuição à qual está associado. Um dos critérios para idenficar outliers consiste em encontrar a **distância interquantil** (IQR), ou seja, a diferença entre o terceiro (Q3) e o primeiro quartis (Q1) da distribuição, e tomar como outliers todos os pontos abaixo do Limite Inferior (LI = Q1 - 1.5*IQR  ), ou acima do Limite Superior (LS = Q3 + 1.5*IQR).

![image.png](https://s3-sa-east-1.amazonaws.com/lcpi/0d8a7b04-b982-4e6b-9fc7-fbb062247d8d.png)


<img src = "https://blog.curso-r.com/images/posts/banner/outlier.webp" />

Escreva uma função que, dada uma matriz de dados de entrada de dimensões $N_{observações} \times N_{features}$ retorne três requisitos: 
- uma matriz booleana indicando a existência de outliers nos dados de entrada;
- a quantidade de outliers
- quem são os outliers (os valores).

**Algumas definições:**
- um *quantil* divide a distribuição, após ordenados os pontos, segundo algum ponto de corte;
- o **primeiro quartil** é o ponto para o qual 25 % dos valores da distribuição estão abaixo dele;
- o **terceiro quartil** é o ponto para o qual 75 % dos valores da distribuição estão abaixo dele.

Pode ser útil consultar a função **numpy.quantile**.

Exemplo de operação da função:

```python
# Geremos um conjunto de dados qualquer
X = np.random.randn(300,15)
X

>>> array([[-2.02108952,  0.57945921, -2.23074965, ..., -0.60349514,
         0.92180452, -0.15625722],
       [ 0.24904397,  0.03493447,  0.3515052 , ..., -0.46950081,
         0.20361331,  0.02715956],
       [ 0.55902525, -0.48435434,  0.90413414, ..., -0.54425743,
        -0.80769134, -0.07912549],
       ...,
       [-1.04069388, -0.24245725, -2.00308877, ...,  0.4084777 ,
        -1.81516131,  0.39063118],
       [-1.39275097,  0.3989636 ,  0.2926223 , ...,  1.2620666 ,
         0.72262949,  1.50737559],
       [ 0.15922011, -0.79810788, -1.60939896, ..., -0.08214499,
        -0.13167475,  0.15990558]])


# identificamos os requisitos com nossa com nossa função "locate_outliers"
is_outlier, outliers_count, outliers = locate_outliers(X)

is_outlier
>>> array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])

outliers_count
>>> 44

outliers
>>> array([-2.67240384,  3.00270904,  3.62317101,  3.18867865,  2.55581522,
       -2.82091429,  2.8757892 ,  2.70666036,  3.19514999, -3.40550318,
       -3.39825827,  2.6727295 ,  2.54498296, -2.69447104,  3.19521603,
        2.66372172, -2.77444948,  2.77421152,  2.69992869, -2.84831109,
       -2.83695779, -2.45908227,  3.07802106,  2.89314015, -2.68574682,
       -2.85019494,  2.43399574,  2.44291266, -2.92595937, -2.95911074,
       -3.03966003,  2.77543068, -2.67368414, -2.79965402, -3.0501958 ,
       -2.5437387 ,  3.08550649, -3.17666255, -3.05795476, -3.09826467,
        3.1399469 ,  3.18141942,  2.90564257, -2.89505054])

 ``` 

In [46]:
# Solução
def locate_outliers(arg):
    arr = arg.copy()
    observacoes, features = arr.shape
    is_outlier = np.zeros((observacoes, features), dtype=bool)
    outliers = []

    for i in range(features):
        coluna = arr[:, i]
        Q1 = np.percentile(coluna, 25)
        Q3 = np.percentile(coluna, 75)
        IQR = Q3 - Q1

        lim_inf = Q1 - 1.5*IQR
        lim_sup = Q3 + 1.5*IQR

        outliers_coluna = (coluna < lim_inf) | (coluna > lim_sup)
        is_outlier[:, i] = outliers_coluna

        # trouble shooting
        print(f"Feature {i}:")
        print(f"Q1: {Q1}, Q3: {Q3}, IQR: {IQR}")
        print(f"Limite Inferior: {lim_inf}, Limite Superior: {lim_sup}")
        print(f"Outliers na coluna: {coluna[outliers_coluna]}")

        outliers.extend(coluna[outliers_coluna])
    
    outlier_count = len(outliers)

    return is_outlier, outlier_count, outliers

print(locate_outliers(arg=np.random.randn(300, 15)))

Feature 0:
Q1: -0.6274180467353927, Q3: 0.6986264297725779, IQR: 1.3260444765079706
Limite Inferior: -2.6164847614973485, Limite Superior: 2.687693144534534
Outliers na coluna: [-3.32074555  3.0803486 ]
Feature 1:
Q1: -0.6919398671966873, Q3: 0.6745458179433645, IQR: 1.3664856851400518
Limite Inferior: -2.741668394906765, Limite Superior: 2.724274345653442
Outliers na coluna: [-2.86725585  2.8256564  -3.4316643 ]
Feature 2:
Q1: -0.6544465626383329, Q3: 0.6332768730679781, IQR: 1.287723435706311
Limite Inferior: -2.5860317161977995, Limite Superior: 2.564862026627445
Outliers na coluna: [-2.72519701  2.91245063]
Feature 3:
Q1: -0.7409653850247042, Q3: 0.6007204529293431, IQR: 1.3416858379540473
Limite Inferior: -2.753494141955775, Limite Superior: 2.613249209860414
Outliers na coluna: [-2.83849212 -3.03521181 -2.77359943]
Feature 4:
Q1: -0.6710535158310915, Q3: 0.6131121279009601, IQR: 1.2841656437320517
Limite Inferior: -2.597301981429169, Limite Superior: 2.5393605934990378
Outliers n

## Questão 8

Crie um vetor com valores que vão de 1 até 21 de dois em dois, a partir da função arange

In [62]:
arr_vec = np.arange(1, 21, 2)

print(arr_vec)

[ 1  3  5  7  9 11 13 15 17 19]


## Questão 9

Crie um array de 10 com valores aleatórios

In [65]:
arr = np.random.rand(10)
print(arr)

[0.63525172 0.14553026 0.03464723 0.84540611 0.97667743 0.73515141
 0.39147655 0.38022549 0.04796811 0.37516272]


## Questão 10

Em estatística, a normalização de uma distribuição de dados pode ser feita subtraindo o valor médio da distribuição de cada valor do conjunto de dados, dividindo o resultado pelo desvio-padrão da distribuição. Escreva uma função que normalize os dados recebidos por um array numpy qualquer, conforme descrito anteriormente.

In [39]:
def normalizacao_dados(arg):
    arr = arg.copy()
    media = np.mean(arr)
    std = np.std(arr)
    dados_normalizados = (arr-media)/std
    return dados_normalizados

print(normalizacao_dados(arg=np.random.rand(10)))

[-0.56174511 -1.15917515  1.79543727 -1.69611465  0.18608043  0.01095542
  0.49538899 -0.68975292  1.10440352  0.51452221]


## Questão 11

Escreva uma função em numpy que receba um array contendo notas de uma turma de 100 estudantes. Considere que a nota de aprovação da turma é 5.0. A função deve retornar, em um array numpy, nesta ordem:
- a média e o desvio-padrão das notas da turma;
- o número de notas maiores que 7.0;
- o número de reprovações da turma;
- a menor nota da turma;
- a maior nota da turma.

In [38]:
def analisa_notas(notas):
    arr = notas.copy()
    arr = np.round(arr, 2)

    # maior e menor nota
    maior_nota = np.max(arr)
    menor_nota = np.min(arr)

    # media e desvio padrao
    media = np.mean(arr)
    desvio_padrao = np.std(arr)

    # notas maiores que 7 menores que 5
    seven_great = np.sum(arr >= 7.00)
    reprovado = np.sum(arr < 5.00)

    # array de retorno
    return np.array([media, desvio_padrao, seven_great, reprovado, menor_nota, maior_nota])

notas = np.random.uniform(0.00, 10.00, 100)
print(analisa_notas(notas))






[ 5.0599     2.9199964 33.        49.         0.08       9.98     ]
